<?php
/**
 * @file
 * Code for the HotNews! feature.
 */

include_once 'hot_news.features.inc';

/**
 * provides server information to the apps
 *
 * this hook is only called on the current profile
 * RETURN: an array of assoctive server arrays
 */
function hot_news_apps_servers_info() {
  return array(
    'hotapps' => array(
      'title' => 'HotApps!',
      'description' => 'First generation HotApps! for the people.',
      'manifest' => 'http://apps.kalamuna.com/hotapps1',
    ),
  );
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function hot_news_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implementation of hook_views_pre_render()
 */
function hot_news_views_pre_view(&$view, &$display_id, &$args) {

  // Modify the options from the view to add in the current sitename into the RSS feed
  if ($view->name == 'hot_news' && $display_id == 'hot_news_feed') {
    $sitename = variable_get('site_name');
    $view->display_handler->options['title'] = str_replace('!sitename', $sitename, $view->display_handler->options['title']);
    $view->display_handler->options['style_options']['description'] = str_replace('!sitename', $sitename, $view->display_handler->options['style_options']['description']);
  }
}
