name = HotNews!
description = Provides the structure and functionality for an article-based content site, ala a blog or news center.
machine_name = hot_news
version = 7.x-1.0-beta1
author = Kalamuna
author_url = http://www.kalamuna.com
screenshots[] = screenshot.png
logo = logo.png
downloadable = hot_news 7.x-1.0-beta1
dependencies[ctools] = ctools 7.x-1.3
dependencies[panelizer] = panelizer 7.x-3.1
dependencies[panels] = panels 7.x-3.4
dependencies[hot_core] = hot_core 7.x-1.x-dev
dependencies[date] = date 7.x-2.6
dependencies[views] = views 7.x-3.7
dependencies[defaultconfig] = defaultconfig 7.x-1.0-alpha9
dependencies[features] = features 7.x-2.0
dependencies[entity] = entity 7.x-1.1
dependencies[entityreference] = entityreference 7.x-1.0
dependencies[field_group] = field_group 7.x-1.1
dependencies[fieldable_panels_panes] = fieldable_panels_panes 7.x-1.5
dependencies[libraries] = libraries 7.x-2.1
dependencies[panels_breadcrumbs] = panels_breadcrumbs 7.x-2.1
dependencies[pathauto] = pathauto 7.x-1.2
dependencies[token] = token 7.x-1.5
dependencies[pm_existing_pages] = pm_existing_pages 7.x-1.4
dependencies[strongarm] = strongarm 7.x-2.0
dependencies[views_autocomplete_filters] = views_autocomplete_filters 7.x-1.0
dependencies[hot_pages] = hot_pages 7.x-1.x-dev
dependencies[menu_block] = menu_block 7.x-2.3
downloadables[ctools 7.x-1.3] = http://ftp.drupal.org/files/projects/ctools-7.x-1.3.tar.gz
downloadables[panelizer 7.x-3.1] = http://ftp.drupal.org/files/projects/panelizer-7.x-3.1.tar.gz
downloadables[panels ] = http://ftp.drupal.org/files/projects/panels-7.x-3.4.tar.gz
downloadables[hot_core 7.x-1.x-dev] = http://ftp.drupal.org/files/projects/hot_core-7.x-1.x-dev.tar.gz
downloadables[date 7.x-2.6] = http://ftp.drupal.org/files/projects/date-7.x-2.6.tar.gz
downloadables[views 7.x-3.7] = http://ftp.drupal.org/files/projects/views-7.x-3.7.tar.gz
downloadables[defaultconfig 7.x-1.0-alpha9] = http://ftp.drupal.org/files/projects/defaultconfig-7.x-1.0-alpha9.tar.gz
downloadables[features 7.x-2.0] = http://ftp.drupal.org/files/projects/features-7.x-2.0.tar.gz
downloadables[entity 7.x-1.1] = http://ftp.drupal.org/files/projects/entity-7.x-1.1.tar.gz
downloadables[entityreference 7.x-1.0] = http://ftp.drupal.org/files/projects/entityreference-7.x-1.0.tar.gz
downloadables[field_group 7.x-1.1] = http://ftp.drupal.org/files/projects/field_group-7.x-1.1.tar.gz
downloadables[fieldable_panels_panes ] = http://ftp.drupal.org/files/projects/fieldable_panels_panes-7.x-1.5.tar.gz
downloadables[libraries 7.x-2.1] = http://ftp.drupal.org/files/projects/libraries-7.x-2.1.tar.gz
downloadables[panels_breadcrumbs 7.x-2.1] = http://ftp.drupal.org/files/projects/panels_breadcrumbs-7.x-2.1.tar.gz
downloadables[pathauto 7.x-1.2] = http://ftp.drupal.org/files/projects/pathauto-7.x-1.2.tar.gz
downloadables[token 7.x-1.5] = http://ftp.drupal.org/files/projects/token-7.x-1.5.tar.gz
downloadables[pm_existing_pages 7.x-1.4] = http://ftp.drupal.org/files/projects/pm_existing_pages-7.x-1.4.tar.gz
downloadables[strongarm 7.x-2.0] = http://ftp.drupal.org/files/projects/strongarm-7.x-2.0.tar.gz
downloadables[views_autocomplete_filters 7.x-1.0] = http://ftp.drupal.org/files/projects/views_autocomplete_filters-7.x-1.0.tar.gz
downloadables[hot_pages 7.x-1.x-dev] = http://ftp.drupal.org/files/projects/hot_pages-7.x-1.x-dev.tar.gz
downloadables[menu_block 7.x-2.3] = http://ftp.drupal.org/files/projects/menu_block-7.x-2.3.tar.gz
downloadables[hot_news 7.x-1.0-beta1] = https://github.com/kalamuna/hot_news/archive/7.x-1.0-beta1.tar.gz
